siteTitle = "Tesl’ar"
siteDescr = "Столярна майстерня"
siteAuthor = "Ihor Orlovskyi"

siteLinkedinUrl = ""
siteFbUrl = "https://www.facebook.com/teslar.com.ua"
siteGithubUrl = ""
siteSoundcloudUrl = ""
siteInstagramUrl = ""
siteGpUrl = ""
siteTwitterUrl = ""

poweredUrl = 'http://rooooster.com'
poweredTitle = 'Rooster Studio'

linkPrefix = "/teslar-react"
